# Sets the base image
From node:18.14-slim

# Create directory to house our image’s application code
WORKDIR /app

# Copies the package.json file into "/server" and runs npm i
COPY ./package.json ./package.json
COPY ./.env ./.env
COPY ./index.js ./index.js
COPY ./seeds.js ./seeds.js
COPY ./models ./models
COPY ./controllers ./controllers
COPY ./routes ./routes
RUN npm install

# Exports
EXPOSE 5000:5000

# Runs "node server.js" after the above step is completed
CMD ["npm", "start"]